### ISSUE TITLE
JIT initialization and shutdown is not done transparently

### ISSUE THREAD

**Issue by aviansie-ben** [wasmjit-omr/wasmjit-omr#10]
Currently, calling `initializeJit` and `shutdownJit` is the responsibility of the program making use of wasmjit-omr. However, this requires source code changes to any program that previously embedded the WABT interpreter to support wasmjit-omr.

A better solution would be to find a way to manage the lifetime of the JIT transparently from within `libwabt`. Right now, this is not done since we have not yet found a clear location to make these calls to ensure that the lifetime of the JIT is correct.

**Comment by aviansie-ben** [comment]
From a cursory look, I've identified the [`wabt::Environment`](https://github.com/wasmjit-omr/wasmjit-omr/blob/62c119a6e81efa5d9be119532be027ac3d8e565c/src/interp.h#L333) class as a potential candidate for hooking initialization and shutdown into. That class seems to be designed for encompassing the entire state of a particular WebAssembly instance and is shared across WebAssembly threads that operate in the same context. If we hook JIT initialization to the constructor and shutdown to the destructor, that should ensure that the JIT is always initialized whenever the interpreter is invoked.

The only potential problem I see here is that multiple of these might exist in more complicated applications to handle sandboxing different WebAssembly environments from each other.

@Leonardo2718 thoughts?

**Comment by Leonardo2718** [comment]
I briefly looked into this a while ago and I agree that `wabt::Environment` seems like a good candidate for handling JIT initialization and shutdown.

In addition to the problem you already mentioned, I am also concerned that there might be problems with per-thread setup and cleanup. However, I don't know enough about how threads are handled/implemented to be sure. Since we are starting off by only handling one thread, we can investigate the implications in more detail later on.
