### ISSUE TITLE
Cache JIT function entry points to avoid unnecessary recompilation

### ISSUE THREAD

**Issue by Leonardo2718** [wasmjit-omr/wasmjit-omr#21]
The entry points to JIT compiled function should be stored in a map that uses WABT function offsets as keys. The next time a function is called, the map should be checked to see if it contains a JITed body for it and only compile it if it does not.

**Comment by Leonardo2718** [comment]
@aviansie-ben, any thoughts whether the map should be in `wabt::interp::Environment` or `wabt::interp::Thread`?

**Comment by aviansie-ben** [comment]
I'm leaning towards `wabt::interp::Environment` as the better option, since it already seems to be used to keep track of all function-related information. While our current implementation of JIT compilation can't handle sharing a JITted function between multiple threads, I expect that's something we'll want to fix at some point.

On top of that, WABT's threading implementation seems somewhat incomplete right now anyway. Adding another thing that breaks when threading is enabled at this point doesn't seem like too big of a deal to me.

**Comment by Leonardo2718** [comment]
Agreed.
