### ISSUE TITLE
Disable failing CI builds

### ISSUE THREAD

**Issue by Leonardo2718** [wasmjit-omr/wasmjit-omr#34]
Some CI builds are failing because of issues not directly related to the JIT. These should be disabled to allow builds to pass and to avoid using too many resources unnecessarily. Builds that should be disabled include:

- `gcc-i686` because of JitBuilder 32-bit build issues
- `SANITIZER=asan` because it is reporting known/intentional issues in the Eclipse OMR compiler
- `SANITIZER=lsan` because it is reporting known/intentional issues in the Eclipse OMR compiler

In addition, although the OSX build is passing, it's taking a very long time to complete. It might, therefore, be worth disabling to keep build times down.

**Comment by aviansie-ben** [comment]
I agree regarding disabling the 32-bit build. As for the sanitizer builds, we should be able to silence their failures without disabling them by adding known/intentional leaks to a [suppressions fie](https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer#suppressions).

As a side note, I think we can also safely disable the `SANITIZER=lsan` build anyway to reduce build times, since the `SANITIZER=asan` build already does memory leak detection.
